services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8080
      DATABASE_URL: postgres://postgres:postgres@db:5432/agnos?sslmode=disable
      JWT_SECRET: super-secret-key
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agnos
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agnos"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - backend
  #   depends_on:
  #     - db

  nginx:
    image: nginx:1.30.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
